/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

import type { PostContent } from "./PayloadPostTypes";

// eslint-disable-next-line @typescript-eslint/no-empty-interface
export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title?: string;
  slug?: string;
  icon?: Icon;
  author?: string | User;
  publishedDate?: string;
  tags?: string[] | Tag[];
  content?: PostContent[];
  accordions: {
    accordionheader: string;
    accordionItems: {
      accordionitemheader?: string;
      accordionitemcontent: PostContent[];
      id?: string;
    }[];
    id?: string;
  }[];
  status?: "draft" | "published";
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "icon".
 */
export interface Icon {
  id: string;
  name?: string;
  value?: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  name?: string;
}
